export const countryList = [
	{ id: 1, name: "Afghanistan" },
	{ id: 2, name: "Albania" },
	{ id: 3, name: "Algeria" },
	{ id: 4, name: "Andorra" },
	{ id: 5, name: "Angola" },
	{ id: 6, name: "Antigua and Barbuda" },
	{ id: 7, name: "Argentina" },
	{ id: 8, name: "Armenia" },
	{ id: 9, name: "Australia" },
	{ id: 10, name: "Austria" },
	{ id: 11, name: "Azerbaijan" },
	{ id: 12, name: "Bahamas" },
	{ id: 13, name: "Bahrain" },
	{ id: 14, name: "Bangladesh" },
	{ id: 15, name: "Barbados" },
	{ id: 16, name: "Belarus" },
	{ id: 17, name: "Belgium" },
	{ id: 18, name: "Belize" },
	{ id: 19, name: "Benin" },
	{ id: 20, name: "Bhutan" },
	{ id: 21, name: "Bolivia" },
	{ id: 22, name: "Bosnia and Herzegovina" },
	{ id: 23, name: "Botswana" },
	{ id: 24, name: "Brazil" },
	{ id: 25, name: "Brunei Darussalam" },
	{ id: 26, name: "Bulgaria" },
	{ id: 27, name: "Burkina Faso" },
	{ id: 28, name: "Burundi" },
	{ id: 29, name: "Cabo Verde" },
	{ id: 30, name: "Cambodia" },
	{ id: 31, name: "Cameroon" },
	{ id: 32, name: "Canada" },
	{ id: 33, name: "Central African Republic" },
	{ id: 34, name: "Chad" },
	{ id: 35, name: "Chile" },
	{ id: 36, name: "China" },
	{ id: 37, name: "Colombia" },
	{ id: 38, name: "Comoros" },
	{ id: 39, name: "Congo" },
	{ id: 40, name: "Costa Rica" },
	{ id: 41, name: "Côte d'Ivoire" },
	{ id: 42, name: "Croatia" },
	{ id: 43, name: "Cuba" },
	{ id: 44, name: "Cyprus" },
	{ id: 45, name: "Czech Republic" },
	{ id: 46, name: "Democratic People's Republic of Korea" },
	{ id: 47, name: "Democratic Republic of the Congo" },
	{ id: 48, name: "Denmark" },
	{ id: 49, name: "Djibouti" },
	{ id: 50, name: "Dominica" },
	{ id: 51, name: "Dominican Republic" },
	{ id: 52, name: "Ecuador" },
	{ id: 53, name: "Egypt" },
	{ id: 54, name: "El Salvador" },
	{ id: 55, name: "Equatorial Guinea" },
	{ id: 56, name: "Eritrea" },
	{ id: 57, name: "Estonia" },
	{ id: 58, name: "Eswatini" },
	{ id: 59, name: "Ethiopia" },
	{ id: 60, name: "Fiji" },
	{ id: 61, name: "Finland" },
	{ id: 62, name: "France" },
	{ id: 63, name: "Gabon" },
	{ id: 64, name: "Gambia" },
	{ id: 65, name: "Georgia" },
	{ id: 66, name: "Germany" },
	{ id: 67, name: "Ghana" },
	{ id: 68, name: "Greece" },
	{ id: 69, name: "Grenada" },
	{ id: 70, name: "Guatemala" },
	{ id: 71, name: "Guinea" },
	{ id: 72, name: "Guinea-Bissau" },
	{ id: 73, name: "Guyana" },
	{ id: 74, name: "Haiti" },
	{ id: 75, name: "Honduras" },
	{ id: 76, name: "Hungary" },
	{ id: 77, name: "Iceland" },
	{ id: 78, name: "India" },
	{ id: 79, name: "Indonesia" },
	{ id: 80, name: "Iran" },
	{ id: 81, name: "Iraq" },
	{ id: 82, name: "Ireland" },
	{ id: 83, name: "Israel" },
	{ id: 84, name: "Italy" },
	{ id: 85, name: "Jamaica" },
	{ id: 86, name: "Japan" },
	{ id: 87, name: "Jordan" },
	{ id: 88, name: "Kazakhstan" },
	{ id: 89, name: "Kenya" },
	{ id: 90, name: "Kiribati" },
	{ id: 91, name: "Kuwait" },
	{ id: 92, name: "Kyrgyzstan" },
	{ id: 93, name: "Lao People's Democratic Republic" },
	{ id: 94, name: "Latvia" },
	{ id: 95, name: "Lebanon" },
	{ id: 96, name: "Lesotho" },
	{ id: 97, name: "Liberia" },
	{ id: 98, name: "Libya" },
	{ id: 99, name: "Liechtenstein" },
	{ id: 100, name: "Lithuania" },
	{ id: 101, name: "Luxembourg" },
	{ id: 102, name: "Madagascar" },
	{ id: 103, name: "Malawi" },
	{ id: 104, name: "Malaysia" },
	{ id: 105, name: "Maldives" },
	{ id: 106, name: "Mali" },
	{ id: 107, name: "Malta" },
	{ id: 108, name: "Marshall Islands" },
	{ id: 109, name: "Mauritania" },
	{ id: 110, name: "Mauritius" },
	{ id: 111, name: "Mexico" },
	{ id: 112, name: "Micronesia" },
	{ id: 113, name: "Moldova" },
	{ id: 114, name: "Monaco" },
	{ id: 115, name: "Mongolia" },
	{ id: 116, name: "Montenegro" },
	{ id: 117, name: "Morocco" },
	{ id: 118, name: "Mozambique" },
	{ id: 119, name: "Myanmar" },
	{ id: 120, name: "Namibia" },
	{ id: 121, name: "Nauru" },
	{ id: 122, name: "Nepal" },
	{ id: 123, name: "Netherlands" },
	{ id: 124, name: "New Zealand" },
	{ id: 125, name: "Nicaragua" },
	{ id: 126, name: "Niger" },
	{ id: 127, name: "Nigeria" },
	{ id: 128, name: "North Korea" },
	{ id: 129, name: "North Macedonia" },
	{ id: 130, name: "Norway" },
	{ id: 131, name: "Oman" },
	{ id: 132, name: "Pakistan" },
	{ id: 133, name: "Palau" },
	{ id: 134, name: "Palestine" },
	{ id: 135, name: "Panama" },
	{ id: 136, name: "Papua New Guinea" },
	{ id: 137, name: "Paraguay" },
	{ id: 138, name: "Peru" },
	{ id: 139, name: "Philippines" },
	{ id: 140, name: "Poland" },
	{ id: 141, name: "Portugal" },
	{ id: 142, name: "Qatar" },
	{ id: 143, name: "Romania" },
	{ id: 144, name: "Russia" },
	{ id: 145, name: "Rwanda" },
	{ id: 146, name: "Saint Kitts and Nevis" },
	{ id: 147, name: "Saint Lucia" },
	{ id: 148, name: "Saint Vincent and the Grenadines" },
	{ id: 149, name: "Samoa" },
	{ id: 150, name: "San Marino" },
	{ id: 151, name: "Sao Tome and Principe" },
	{ id: 152, name: "Saudi Arabia" },
	{ id: 153, name: "Senegal" },
	{ id: 154, name: "Serbia" },
	{ id: 155, name: "Seychelles" },
	{ id: 156, name: "Sierra Leone" },
	{ id: 157, name: "Singapore" },
	{ id: 158, name: "Slovakia" },
	{ id: 159, name: "Slovenia" },
	{ id: 160, name: "Solomon Islands" },
	{ id: 161, name: "Somalia" },
	{ id: 162, name: "South Africa" },
	{ id: 163, name: "South Korea" },
	{ id: 164, name: "South Sudan" },
	{ id: 165, name: "Spain" },
	{ id: 166, name: "Sri Lanka" },
	{ id: 167, name: "Sudan" },
	{ id: 168, name: "Suriname" },
	{ id: 169, name: "Sweden" },
	{ id: 170, name: "Switzerland" },
	{ id: 171, name: "Syria" },
	{ id: 172, name: "Taiwan" },
	{ id: 173, name: "Tajikistan" },
	{ id: 174, name: "Tanzania" },
	{ id: 175, name: "Thailand" },
	{ id: 176, name: "Timor-Leste" },
	{ id: 177, name: "Togo" },
	{ id: 178, name: "Tonga" },
	{ id: 179, name: "Trinidad and Tobago" },
	{ id: 180, name: "Tunisia" },
	{ id: 181, name: "Turkey" },
	{ id: 182, name: "Turkmenistan" },
	{ id: 183, name: "Tuvalu" },
	{ id: 184, name: "Uganda" },
	{ id: 185, name: "Ukraine" },
	{ id: 186, name: "United Arab Emirates" },
	{ id: 187, name: "United Kingdom" },
	{ id: 188, name: "United States of America" },
	{ id: 189, name: "Uruguay" },
	{ id: 190, name: "Uzbekistan" },
	{ id: 191, name: "Vanuatu" },
	{ id: 192, name: "Vatican City (Holy See)" },
	{ id: 193, name: "Venezuela" },
	{ id: 194, name: "Vietnam" },
	{ id: 195, name: "Yemen" },
	{ id: 196, name: "Zambia" },
	{ id: 197, name: "Zimbabwe" },
];
